version: "3.9"
services:
  
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_BASE_URL=http://localhost:80/v1/
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env