version: "3.9"
services:
  
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000