import { Dialog, DialogTitle, DialogContent, DialogContentText, TextField, DialogActions, Button } from "@mui/material";

const MfaDialog = ({open, handleClose, setMfaCode, handleSubmit} : {open: any, handleClose: any, setMfaCode: any, handleSubmit: any}) => {
  return (
    <>
        <Dialog open={open} onClose={handleClose}>
            <DialogTitle>Enter MFA Code</DialogTitle>
            <DialogContent>
            <DialogContentText>
                Please enter the MFA code generated by your authenticator app.
            </DialogContentText>
            <TextField
                autoFocus
                margin="dense"
                id="mfaCode"
                label="MFA Code"
                type="text"
                fullWidth
                onChange={(e) => setMfaCode(e.target.value)}
            />
            </DialogContent>
            <DialogActions>
            <Button onClick={handleClose}>Cancel</Button>
            <Button onClick={handleSubmit}>Confirm</Button>
            </DialogActions>
        </Dialog>
    </>
  );
};

export default MfaDialog;
